import path from "node:path";
import { fileURLToPath } from "node:url";
import { GlobalFonts } from "@napi-rs/canvas";
import generatedCatalog from "./fontCatalog.generated.json" with { type: "json" };

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export interface FontFamilyCatalogEntry {
  family: string;
  weights: { weight: number; fileName: string; format: string }[];
}

// Generated by scripts/sync-font-library.mjs from font-library/ — do not
// hand-edit fontCatalog.generated.json, edit font-library/ and re-run the
// script. Keep in sync with apps/editor/src/fontAssets.ts.
export const FONT_CATALOG: FontFamilyCatalogEntry[] = generatedCatalog;

let registered = false;

/** Registers every embedded font with Skia's global font manager so
 * ctx.font (e.g. "bold 32px Inter") resolves to the right weight's file
 * instead of silently substituting a system font — call once at startup,
 * before any render. Idempotent. */
export function registerEmbeddedFonts(): void {
  if (registered) return;
  registered = true;
  for (const { family, weights } of FONT_CATALOG) {
    for (const { fileName } of weights) {
      const filePath = path.join(__dirname, "../assets/fonts", family, fileName);
      GlobalFonts.registerFromPath(filePath, family);
    }
  }
}
