import path from "node:path";
import { fileURLToPath } from "node:url";
import generatedCatalog from "./frameCatalog.generated.json" with { type: "json" };

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export interface FrameAsset {
  id: string;
  name: string;
  category: string;
  categoryLabel: string;
  fileName: string;
}

// Generated by scripts/sync-frame-library.mjs from frame-library/ — do not
// hand-edit frameCatalog.generated.json, edit frame-library/ and re-run the
// script. Keep in sync with apps/editor/src/frameAssets.ts; see README's
// "Adding frames" section for why the catalog (and its backing images) are
// published to both consumers rather than shared at runtime.
export const FRAME_ASSETS: FrameAsset[] = generatedCatalog;

/** Resolves a catalog assetId to an absolute file path for @napi-rs/canvas's
 * loadImage. Undefined for unknown ids — callers fall back to the flat-tint
 * placeholder in that case. */
export function getFrameAssetPath(assetId: string): string | undefined {
  const asset = FRAME_ASSETS.find((a) => a.id === assetId);
  return asset ? path.join(__dirname, "../assets/frames", asset.category, asset.fileName) : undefined;
}
