import path from "node:path";
import { fileURLToPath } from "node:url";
import generatedCatalog from "./rarityCatalog.generated.json" with { type: "json" };

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export interface RarityAsset {
  id: string;
  label: string;
  fileName: string;
}

// Generated by scripts/sync-rarity-library.mjs from rarity-library/ — do
// not hand-edit rarityCatalog.generated.json, edit rarity-library/ and
// re-run the script. Keep in sync with apps/editor/src/rarityAssets.ts.
export const RARITY_ASSETS: RarityAsset[] = generatedCatalog;

export function getRarityAsset(id: string): RarityAsset | undefined {
  return RARITY_ASSETS.find((a) => a.id === id);
}

/** Resolves a catalog rarity id to an absolute disk path @napi-rs/canvas's
 * loadImage() can read. Undefined for unknown ids — callers fall back to
 * `layer.src` in that case, same as an unresolved frame assetId falls
 * back to a tint placeholder. */
export function getRarityAssetPath(id: string): string | undefined {
  const asset = getRarityAsset(id);
  return asset ? path.join(__dirname, "../assets/rarity", asset.fileName) : undefined;
}
