import path from "node:path";
import { fileURLToPath } from "node:url";
import generatedCatalog from "./symbolCatalog.generated.json" with { type: "json" };

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export interface SymbolAsset {
  id: string;
  label: string;
  fileName: string;
}

// Generated by scripts/sync-symbol-library.mjs from symbol-library/ — do
// not hand-edit symbolCatalog.generated.json, edit symbol-library/ and
// re-run the script. Keep in sync with apps/editor/src/symbolAssets.ts.
export const SYMBOL_ASSETS: SymbolAsset[] = generatedCatalog;

function normalizeToken(token: string): string {
  return token.trim().toLowerCase().replace(/\//g, "-");
}

export function getSymbolAsset(token: string): SymbolAsset | undefined {
  const id = normalizeToken(token);
  return SYMBOL_ASSETS.find((a) => a.id === id);
}

/** Resolves a {token} to an absolute disk path @napi-rs/canvas's
 * loadImage() can read. Undefined for a token with no matching asset. */
export function getSymbolAssetPath(token: string): string | undefined {
  const asset = getSymbolAsset(token);
  return asset ? path.join(__dirname, "../assets/symbols", asset.fileName) : undefined;
}

/** A generic mana token — {0}, {1}, {2}, ... any non-negative integer —
 * renders as a drawn circle + digits instead of a library asset. */
export function isGenericManaToken(token: string): boolean {
  return /^\d+$/.test(token.trim());
}
