import generatedCatalog from "./fontCatalog.generated.json";

export interface FontFamilyCatalogEntry {
  family: string;
  weights: { weight: number; fileName: string; format: string }[];
}

// Generated by scripts/sync-font-library.mjs from font-library/ — do not
// hand-edit fontCatalog.generated.json, edit font-library/ and re-run the
// script. Keep in sync with services/render/src/fontAssets.ts. See
// README's "Adding fonts" section.
export const FONT_CATALOG: FontFamilyCatalogEntry[] = generatedCatalog;

export const EMBEDDED_FONT_FAMILIES: string[] = FONT_CATALOG.map((f) => f.family);

/** Fonts not embedded via font-library/ — available only if the visitor's
 * OS/browser happens to have them installed. Kept as extra choices, but
 * text set in one of these can render differently (or fall back silently)
 * between the editor, another visitor's browser, and the print export. */
export const SYSTEM_FONT_FALLBACKS = ["Arial", "Georgia", "Times New Roman", "Courier New", "Trebuchet MS"];
