import generatedCatalog from "./frameCatalog.generated.json";
import { ASSET_BASE } from "./assetBase";

export interface FrameAsset {
  id: string;
  name: string;
  category: string;
  categoryLabel: string;
  fileName: string;
}

// Generated by scripts/sync-frame-library.mjs from frame-library/ — do not
// hand-edit frameCatalog.generated.json, edit frame-library/ and re-run the
// script. Keep in sync with services/render/src/frameAssets.ts; see
// README's "Adding frames" section for why the catalog (and its backing
// images) are published to both consumers rather than shared at runtime.
export const FRAME_ASSETS: FrameAsset[] = generatedCatalog;

export const FRAME_CATEGORIES: string[] = Array.from(new Set(FRAME_ASSETS.map((a) => a.category)));

export function getFrameAsset(assetId: string): FrameAsset | undefined {
  return FRAME_ASSETS.find((a) => a.id === assetId);
}

/** Resolves a catalog assetId to a URL Konva/the <img> loader can fetch.
 * Undefined for unknown ids (e.g. legacy designs) — callers fall back to
 * the flat-tint placeholder in that case. */
export function getFrameAssetUrl(assetId: string): string | undefined {
  const asset = getFrameAsset(assetId);
  return asset ? `${ASSET_BASE}frames/${asset.category}/${asset.fileName}` : undefined;
}
