import generatedCatalog from "./rarityCatalog.generated.json";

export interface RarityAsset {
  id: string;
  label: string;
  fileName: string;
}

// Generated by scripts/sync-rarity-library.mjs from rarity-library/ — do
// not hand-edit rarityCatalog.generated.json, edit rarity-library/ and
// re-run the script. Keep in sync with services/render/src/rarityAssets.ts.
export const RARITY_ASSETS: RarityAsset[] = generatedCatalog;

export function getRarityAsset(id: string): RarityAsset | undefined {
  return RARITY_ASSETS.find((a) => a.id === id);
}

/** Resolves a catalog rarity id to a URL Konva/the <img> loader can fetch.
 * Undefined for unknown ids. */
export function getRarityAssetUrl(id: string): string | undefined {
  const asset = getRarityAsset(id);
  return asset ? `/rarity/${asset.fileName}` : undefined;
}
