import generatedCatalog from "./symbolCatalog.generated.json";
import { ASSET_BASE } from "./assetBase";

export interface SymbolAsset {
  id: string;
  label: string;
  fileName: string;
}

// Generated by scripts/sync-symbol-library.mjs from symbol-library/ — do
// not hand-edit symbolCatalog.generated.json, edit symbol-library/ and
// re-run the script. Keep in sync with services/render/src/symbolAssets.ts.
export const SYMBOL_ASSETS: SymbolAsset[] = generatedCatalog;

/** {token} -> catalog id: lowercase, "/" -> "-" (so {W/U} looks up "w-u"). */
function normalizeToken(token: string): string {
  return token.trim().toLowerCase().replace(/\//g, "-");
}

export function getSymbolAsset(token: string): SymbolAsset | undefined {
  const id = normalizeToken(token);
  return SYMBOL_ASSETS.find((a) => a.id === id);
}

/** Resolves a {token} to a URL Konva/the <img> loader can fetch. Undefined
 * for a token with no matching symbol-library asset. */
export function getSymbolAssetUrl(token: string): string | undefined {
  const asset = getSymbolAsset(token);
  return asset ? `${ASSET_BASE}symbols/${asset.fileName}` : undefined;
}

/** A generic mana token — {0}, {1}, {2}, ... any non-negative integer, or
 * a variable cost ({X}, {Y}, {Z}) — renders as a drawn circle + the
 * digits/letter instead of a library asset, so arbitrary numbers (and the
 * handful of variable-cost letters) don't need one SVG file per value. */
export function isGenericManaToken(token: string): boolean {
  return /^(\d+|[XYZ])$/i.test(token.trim());
}
