import generatedCatalog from "./textTemplateCatalog.generated.json";

export interface TextFieldTemplate {
  id: string;
  label: string;
  defaultContent: string;
  /** mm, relative to the CUT/trim corner (0,0 = the finished card's own
   * top-left corner) — NOT the full-bleed canvas. Toolbar.tsx adds the
   * cut-to-canvas offset when placing these. */
  x: number;
  y: number;
  width: number;
  height: number;
  fontSizePt: number;
  /** Optional "fit within this range" boundaries — when both are set, a
   * shrink-mode layer created from this field searches from maxFontSizePt
   * down to minFontSizePt for the largest size that fits, instead of
   * sitting fixed at fontSizePt: short content grows to fill the box
   * rather than looking small inside it. Omit either (or both) to keep
   * the original shrink-only-from-fontSizePt behavior. */
  minFontSizePt?: number;
  maxFontSizePt?: number;
  fontWeight: "normal" | "bold";
  isItalic: boolean;
  align: "left" | "center" | "right";
  /** Fill color a text layer created from this field starts with. */
  color: string;
  /** Overrides DEFAULT_FONT_FAMILY (config.ts) for this field specifically
   * when set — e.g. a script face for flavor text. Must name a family
   * that's actually in the font catalog (or a system font), same caveat
   * as DEFAULT_FONT_FAMILY itself. Omit to just use the default. */
  fontFamily?: string;
  /** Optional drop shadow this field starts with — omit entirely for no
   * shadow (the common case; most rules-text-shaped fields read worse
   * with one), or set at least `color` for fields that benefit from one
   * (e.g. a title sitting over busy full-art). `color`'s presence is the
   * on/off switch, same convention as TextLayer.shadowColor itself;
   * offsetXPt/offsetYPt/blurPt/opacity each independently fall back to
   * schema.ts's TextLayer defaults (0/0/1pt/0.75) when omitted, so a
   * template can set just a color and get sensible sizing for free. */
  shadow?: {
    color: string;
    offsetXPt?: number;
    offsetYPt?: number;
    blurPt?: number;
    opacity?: number;
  };
  /** Default value for the new layer's `locked` (position/transform lock)
   * field — omit for the schema default (false, i.e. freely movable).
   * Independent of contentLocked below, and never gated by any user
   * entitlement — see schema.ts's LayerBase doc comments and README's
   * "Field locking" section. */
  locked?: boolean;
  /** Default value for the new layer's `contentLocked` field — omit for
   * the schema default (false, i.e. anyone can edit this field's text).
   * When true, editing the content requires the current user to have
   * Entitlements.canEditLockedContent (apps/editor/src/entitlements.ts)
   * — the "premium" gate. */
  contentLocked?: boolean;
  /** Rules/flavor-text coupling (see rulesFlavorFit.ts) — read only off
   * the "rules" field's own template entry, since rules and flavor
   * together occupy one shared, automatically-sized boundary box rather
   * than each having its own fixed one. All three optional; omitting any
   * (or all) falls back to rulesFlavorFit.ts's own defaults, and a
   * template with no "rules" entry at all just never activates the
   * coupling — rules/flavor (if added independently) keep behaving like
   * any other independent text field.
   *
   * gapAboveTypelineMm: space between the typeline field's bottom edge
   * and the top of the rules/flavor box.
   * gapAboveLegalMm: space between the bottom of the rules/flavor box
   * and whichever of edition/artist/signature sits topmost — and,
   * separately, the minimum clearance kept above the power/toughness
   * field, so the box's bottom edge is naturally raised to stay clear of
   * it entirely rather than needing per-line text wrapping around it.
   * flavorGapLines: gap between the rules block and the flavor block
   * below it, in multiples of the shared line height (so it scales with
   * whatever font size the pair ends up shrinking to).
   */
  gapAboveTypelineMm?: number;
  gapAboveLegalMm?: number;
  flavorGapLines?: number;
}

interface TextTemplateCatalog {
  base: TextFieldTemplate[];
  categories: Record<string, TextFieldTemplate[]>;
}

// Generated by scripts/sync-text-templates.mjs from text-template-library/
// — do not hand-edit textTemplateCatalog.generated.json, edit
// text-template-library/_base.json (the default/fallback set) or
// text-template-library/<frame category>.json (an override for frames in
// that frame-library/ category) and re-run the script. See README's "MTG
// text fields" section.
const CATALOG = generatedCatalog as TextTemplateCatalog;

/** The default/fallback field set — used whenever no frame is present, or
 * the present frame's category has no override of its own yet. */
export const BASE_TEXT_TEMPLATES: TextFieldTemplate[] = CATALOG.base;

/**
 * Resolves the field set that applies for a given frame category (see
 * Toolbar.tsx's `activeFrameCategory`, derived from whatever Frame layer
 * is currently in the design). Every category duplicates `_base.json` the
 * first time `sync-text-templates` sees it, so a field that looks
 * slightly off against one particular frame can be fixed by hand-editing
 * just that category's numbers without touching any other frame's fields.
 */
export function getTextTemplates(frameCategory: string | undefined): TextFieldTemplate[] {
  if (frameCategory && CATALOG.categories[frameCategory]) return CATALOG.categories[frameCategory];
  return CATALOG.base;
}
