import generatedCatalog from "./textTemplateCatalog.generated.json";

export interface TextFieldTemplate {
  id: string;
  label: string;
  defaultContent: string;
  /** mm, relative to the CUT/trim corner (0,0 = the finished card's own
   * top-left corner) — NOT the full-bleed canvas. Toolbar.tsx adds the
   * cut-to-canvas offset when placing these. */
  x: number;
  y: number;
  width: number;
  height: number;
  fontSizePt: number;
  fontWeight: "normal" | "bold";
  align: "left" | "center" | "right";
  /** Fill color a text layer created from this field starts with. */
  color: string;
}

interface TextTemplateCatalog {
  base: TextFieldTemplate[];
  categories: Record<string, TextFieldTemplate[]>;
}

// Generated by scripts/sync-text-templates.mjs from text-template-library/
// — do not hand-edit textTemplateCatalog.generated.json, edit
// text-template-library/_base.json (the default/fallback set) or
// text-template-library/<frame category>.json (an override for frames in
// that frame-library/ category) and re-run the script. See README's "MTG
// text fields" section.
const CATALOG = generatedCatalog as TextTemplateCatalog;

/** The default/fallback field set — used whenever no frame is present, or
 * the present frame's category has no override of its own yet. */
export const BASE_TEXT_TEMPLATES: TextFieldTemplate[] = CATALOG.base;

/**
 * Resolves the field set that applies for a given frame category (see
 * Toolbar.tsx's `activeFrameCategory`, derived from whatever Frame layer
 * is currently in the design). Every category duplicates `_base.json` the
 * first time `sync-text-templates` sees it, so a field that looks
 * slightly off against one particular frame can be fixed by hand-editing
 * just that category's numbers without touching any other frame's fields.
 */
export function getTextTemplates(frameCategory: string | undefined): TextFieldTemplate[] {
  if (frameCategory && CATALOG.categories[frameCategory]) return CATALOG.categories[frameCategory];
  return CATALOG.base;
}
